name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  org-ci:
    uses: LacardLabs/.github/.github/workflows/ci.yml@ef34c38ca6a0e2d8ff94757d962a61fefe418ab9
    with:
      language: none
      run_tests: true
      codeql: false
      sbom: false
    secrets: inherit
